### ISSUE TITLE
데이터셋 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by da-nyee** [Naver-AI-Hackathon/AI-Speech#10]
해커톤 데이터셋을 nsml dataset pull sr-hack-2019-dataset 명령어를 쳐서 다운받으려고 합니다. 하지만 이때 pull 명령어가 작동되지 않습니다. Available commands에 아예 pull이 없는데, 확인부탁드립니다.

**Comment by bluebrush** [comment]
@da-nyee 님, https://github.com/clovaai/speech_hackathon_2019/blob/master/README.md 관련 정보를 업데이트하였습니다. 불편을 드려서 죄송합니다.
