### ISSUE TITLE
nsml submit 관련 ( nsml.data_loader )

### ISSUE THREAD

**Issue by nccaiteam** [Naver-AI-Hackathon/AI-Speech#113]
안녕하세요
다름이 아니라 nsml submit 코드를 테스트하는데 문제가 생겨 이렇게 질문을 드립니다.

현재 nsml run을 통해 모델을 training하였고, submit을 테스트하기 위해

nsml submit -t nsmlteam/KHD_mammon_train/38 3
를 입력했습니다

이에 Building Docker image 까지는 나오지만,
ImportError: No module named 'nsml.data_loader'
라고 뜨면서 에러가 생깁니다

이 에러가 코딩의 실수인지 아님 문제가 있는건지 부탁드립니다..
감사합니다.

**Comment by nsml-admin** [comment]
dataset을 push 할때  `--leaderboard`옵션을 붙이고 올렸어야 하는데   `KHD_mammon_train` 이 데이터셋은 그렇게 올라간게 아닌거같습니다. 

데이터셋을 다시올리셔야할거같습니다.

**Comment by bluebrush** [comment]
![image](https://user-images.githubusercontent.com/12540235/68569473-8375c280-04a1-11ea-8c90-cfe3aad3c248.png)
위 그림에서 1,2,3을 참고하시면 될것같습니다.

**Comment by nccaiteam** [comment]
답변 감사드립니다.
그리고 다른 질문이 또 있는데, data를 push하고나서 경로를 보니까 다음과 같이
'/data/KHD_2019_mammo/train/train'
'/data/KHD_2019_mammo/train/test'
train 폴더가 중복으로 업로드 되었습니다.


'/data/KHD_2019_mammo/train'
'/data/KHD_2019_mammo/test'
예상했던 경로는 다음과 같이 train의 path가 하나 적어야하는데 왜 이렇게 된건지 질문드립니다.

감사합니다
