### ISSUE TITLE
NSML Document website 404 error

### ISSUE THREAD

**Issue by ClovaFlova** [Naver-AI-Hackathon/AI-Speech#12]
NSML Document link (https://n-clair.github.io/airush-docs/_build/html/ko_KR/index.html) 
404 에러 발생하는데 확인 부탁드립니다.

**Comment by bluebrush** [comment]
@ClovaFlova 님, 아래 주소로 변경되었습니다. 
https://n-clair.github.io/ai-docs/_build/html/ko_KR/index.html
