### ISSUE TITLE
NSML Login 오류

### ISSUE THREAD

**Issue by libary753** [Naver-AI-Hackathon/AI-Speech#13]
안녕하세요 DongDang 팀 김용성입니다.

NSML Login 시에 오류가 발생해서 문의드립니다.

NSML login 커맨드로 로그인이 안되어서 NSML 홈페이지(ai.nsml.navercorp.com) 에 로그인을 시도했는데 로그인이 안 되네요 혹시 계정 등록이 되어있는지 확인 부탁드립니다.

Github
mail: libary753@gmail.com
id: libary753

**Comment by nsml-admin** [comment]
안녕하세요
지금 한번해보시겠어요?
계정 libary753 이걸로 등록되었습니다.

**Comment by libary753** [comment]
넵 로그인되었습니다. 감사합니다.
