### ISSUE TITLE
docker 관련 질문 입니다.

### ISSUE THREAD

**Issue by whtngus** [Naver-AI-Hackathon/AI-Speech#14]
setup.py 에서보면 
#nsml: nvcr.io/nvidia/pytorch:19.06-py3
도커를 사용하는것으로 보입니다.  
도커허브에서 검색시 18.02-py3버전 밖에 안보입니다.

질문입니다.
1 
위버전은 도커허브에서 다운로드 및 사용이 불가능한가요?
가능하다면 접근 방법을 알려주세요
2. 
만약 18.02-py3 버전과 차이가 있다면 어떤 차이가있고, 제가 사용하는 도커를 올릴 수있는 방법을 알 수있을까요?
3.  
2번이 가능하다면
도커를 불러올 수 있는 용량이나 제한 사항이 있는지 알고싶습니다.

**Comment by nsml-admin** [comment]
1. 아래 링크를 참조해주시기 바랍니다.
https://ngc.nvidia.com/catalog/containers/nvidia:pytorch/tags

2. https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html 링크의 
`pip로 install이 불가능한 경우` 를 참고해 주시기 바랍니다.
    도커 이미지의 용량은 제한이 없지만 추후에 스토리지 관련된 문제가 생긴다면 용량순으로 가장높은 우선순위로 지워질 가능성은 있습니다.

감사합니다.

**Comment by whtngus** [comment]
답변 감사합니다.
