### ISSUE TITLE
데이터셋 개수 확인 가능한가요?

### ISSUE THREAD

**Issue by SaewonY** [Naver-AI-Hackathon/AI-Speech#15]
현재 스코어를 산출하는 test set의 개수에 대해서 확인을 할 수 있을까요?
명시된 곳이 있는지, 있다면 제가 발견 못한건지 궁금합니다.
감사합니다.

**Comment by ClovaAIAdmin** [comment]
TestSet은 1,020개입니다.
감사합니다.

**Comment by SaewonY** [comment]
@ClovaAIAdmin 확인 감사합니다.
