### ISSUE TITLE
credit 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by SaewonY** [Naver-AI-Hackathon/AI-Speech#16]
현재 저희 팀 credit이 약 200 밖에 남지 않았습니다.

추가 credit을 받을 수 있는지, 그리고 관련 정책이 궁금합니다.

감사합니다.

**Comment by SaewonY** [comment]
크레딧 부족으로 학습 도중에 kill이 됐네요

**Comment by bluebrush** [comment]
@SaewonY 님, 불편을 드려서 죄송합니다.  10일치 credit을 한번에 충전하였습니다. 참고부탁드립니다. 이후 credit 정책에 대한 별도 공지를 하도록 하겠습니다.

**Comment by SaewonY** [comment]
@bluebrush 감사합니다
