### ISSUE TITLE
nsml docker image 오류

### ISSUE THREAD

**Issue by elzino** [Naver-AI-Hackathon/AI-Speech#17]
안녕하세요 39번팀의 3번 세션이 시작하려고 하니
10분째 Allocating ! 만 계속 뜨면서 멈춰지지도 않네요
어떻게 해야하나요?

**Comment by HanSeokhyeon** [comment]
저희도 같은 현상으로 5분째 안되고 있습니다...

**Comment by bluebrush** [comment]
@elzino , @Hackoperation 님, 불편을 드려서 죄송합니다. 
각 GPU node에서 최소 실행시 docker image download 및 설치요구사항에 명시한 모듈들이 설치되기까지 다소 시간이 소요됩니다. docker image의 경우, 특정 node에서 최초 실행시에만 느리며, 동일 NODE를 재사용할 경우 상대적으로 빠르게 진행됩니다. 이부분 참고하시면 좋을 것 같습니다.

**Comment by HanSeokhyeon** [comment]
최소 시간이라고 하기엔 30분째 allocating!이 뜨고 있는데 진행되고 있는게 맞나요??

**Comment by bluebrush** [comment]
@HanSeokhyeon 님, session ID 전달 가능하실까요? 또는 웹화면의 url 주셔도 됩니다.

**Comment by HanSeokhyeon** [comment]
team172/sr-hack-2019-dataset/3
team172/sr-hack-2019-dataset/4
session ID가 이거 말씀하시는 건가요?

https://ai.nsml.navercorp.com/terminal/team172/sr-hack-2019-dataset/3
https://ai.nsml.navercorp.com/terminal/team172/sr-hack-2019-dataset/4
url은 여기 있습니다.

**Comment by bluebrush** [comment]
@HanSeokhyeon 님, 두 세션 모두 강제로 삭제하였습니다. 
실행하실 때, session 시작 단계(설치)에서 Ctrl + C 같은 인터럽터를 걸어서 발생한 상황으로 보입니다. 다시 실행하신 수, CLI에 인터럽터 없이 잠시 기다리시면 실행될 것으로 예상됩니다.

**Comment by HanSeokhyeon** [comment]
@bluebrush 님, 감사합니다!!

**Comment by mulkong** [comment]
강제로 Session Kill을 해주시면 해결됩니다!
