### ISSUE TITLE
librosa library version 이슈

### ISSUE THREAD

**Issue by elzino** [Naver-AI-Hackathon/AI-Speech#18]
librosa library를 사용하는데 버전이 0.7보다 낮은 거 같습니다
그래서 현재 사용하고 싶은 기능을 못쓰고 있는데 librosa library 0.7로 업데이트 해주실 수 있나요?
아니면 제가 직접 해야되는건가요?

**Comment by elzino** [comment]
requirement.txt를 통해 liborsa update는 해결했는데 다시 
 OSError('sndfile library not found') 에러가 발생하네요

sudo apt-get install libsndfile1 로 해결해야할 거 같은데
도커 이미지에 추가가 가능할까요?

**Comment by nsml-admin** [comment]
안녕하세요.

1. 해당 패키지를 추가한 도커이미지를 직접만드시는 방법 ( https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html#prepare-a-session-environment 링크의 `pip로 install이 불가능한 경우` 참고)
2. apt-get 으로 실행할때마다 설치하는 방법  (https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html#prepare-a-session-environment 링크의 `apt-get 으로 패키지를 설치해야 할 필요가 있을 경우` 참고)

이 있을것 같습니다.

감사합니다.
