### ISSUE TITLE
NSML 미등록 이슈

### ISSUE THREAD

**Issue by Dohppak** [Naver-AI-Hackathon/AI-Speech#21]
## NSML 미등록 이슈

NSML에 github계정을 통해 등록하려는데 아래와 같은 메세지가 나옵니다
You are not a registered user. Please contact the administrator. 
(dl_nsml_alpha@navercorp.com )

dl_naver_aihack@navercorp.com 으로 메일을 남겼습니다. 혹시 이문제 해결 가능할까요?

제 깃허브 계정은

id : dohppak
email : seung20764298@gmail.com 입니다.

**Comment by nsml-admin** [comment]
vaild계정 체크하는 부분에서 가입요청시 기입했던 계정에 대소문자가 달랐었네요!
지금 한번 확인해보시겠어요? 아래계정으로 입력하셔야합니다!
"Dohppak"

**Comment by Dohppak** [comment]
INFO[2019/09/19 12:37:50.695] Welcome to NSML!                             
해결했습니다!
