### ISSUE TITLE
nsml 클라우드 디스크 용량 관련 문의

### ISSUE THREAD

**Issue by alberto-hong** [Naver-AI-Hackathon/AI-Speech#26]
안녕하세요. Naver 관계자님.

현재 .wav 파일을 preprocessing 할때,
매 batch를 뽑을때 마다 하면 epoch마다 같은 작업이 반복되어,
시간이 비효율적인데요.

.wav 파일들에 대해서 preprocessing을 한 파일을 .npy로 따로 저장하여 
batching을 할때 단순 loading만 하려고 하는데
이와 관련 nsml 클라우드에서 사용할 수 있는 디스크 용량을 알고 싶습니다.

**Comment by bluebrush** [comment]
@alberto-hong  님, disk 용량 제한은 특별히 없습니다. 너무 커지만 않다면 가능하고, 크기에 문제가 있으면, session 삭제로 제거 가능합니다. 권장 규모는 100GB 이하 입니다.
