### ISSUE TITLE
[문의]지원관련하여 메일은 보내지 않는지요

### ISSUE THREAD

**Issue by hygjob** [Naver-AI-Hackathon/AI-Speech#3]
안녕하세요
고현영이라고 합니다. 

3차 AI naver hackathon에 지원을 했는데요.

1. 따로 지원했다고 메일은 보내주지 않는지요?

2. 팀원을 추가하려고 하는데 참가정보를 수정하려는데 응모이력이 없다고 나옵니다.
어떻게 해야 하는지요?

**Comment by GT-KIM** [comment]
안녕하세요.

여기 말고 신청 페이지에 있는 QnA 메일에 문의드리면 될 것 같습니다.
저도 여기에 질문했다가 메일로 다시 질문했었는데, 메일이 훨씬 빨리 답변해 주시더라구요.

**Comment by hygjob** [comment]
아 그렇군요. 고맙습니다. 메일을 보내도록 하겠습니다.
