### ISSUE TITLE
토크나이저 저장을 위해 nsml.save 호출시 에러

### ISSUE THREAD

**Issue by kevhahn97** [Naver-AI-Hackathon/AI-Speech#30]
![image](https://user-images.githubusercontent.com/5675167/65231084-fd28aa00-db09-11e9-90ca-e70b46442b32.png)
안녕하세요, 토크나이저 학습 후 모델을 저장하려고 하니 위와 같은 에러가 뜹니다. 혹시 어떤 문제인지 도움 받을 수 있을까요?
save_fn 정의부분은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/5675167/65232456-22b6b300-db0c-11e9-92c1-0c1bd1848d4f.png)

**Comment by nsml-admin** [comment]
안녕하세요.
실제 코드를 봐야할것같습니다 세션이름을 알려주시면 확인해보겠습니다.

**Comment by kevhahn97** [comment]
team69/sr-hack-2019-dataset/123
으로 확인해주시면 감사하겠습니다.

**Comment by nsml-admin** [comment]
아래와 같이 바꾸고 실행해보시기 바랍니다.
```python
    nsml.bind(save=save_and_train_tokenizer)
    nsml.save('tokenizer')
```

**Comment by kevhahn97** [comment]
감사합니다
