### ISSUE TITLE
train 시작 안되고 멈춰있는 것 관련 질문

### ISSUE THREAD

**Issue by kaen2891** [Naver-AI-Hackathon/AI-Speech#31]
안녕하세요.

loader 부분에서 get_spectrogram_feature의 내용을 저희가 변경하여,
나머지 구조는 그대로 유지한 채 main.py를 실행하였는데 아래와 같이 뜬 상태로 10분째 멈춰있습니다.

안의 내용은 spectrogram을 librosa 라이브러리 이용하여 다른 형태로 바꾸는 내용이고,
setup.py 에 librosa==0.6.3 을 install_requires에 넣어서 사용하고있습니다.

```
[2019-09-19 10:47:24,018 main.py:392 - main()] start
[2019-09-19 10:47:24,020 main.py:113 - train()] train() start
```
이를 어떻게 해결해야 할까요?

감사합니다.

**Comment by kaen2891** [comment]
한 가지 질문 더 드리고 싶은것은, 

librosa를 하였을 경우
위의 결과처럼 무한으로 대기중 상태인지라, torchaudio 를 써보았는데요,
무한 Allowcationg이 뜨는 상황입니다.

이에 대한 답변도 해주시면 감사하겠습니다.

**Comment by HanSeokhyeon** [comment]
안녕하세요 @kaen2891 님!
저희 팀도 같은 현상을 겪었습니다. project의 setup.py를 열어보면 docker image가 

`#nsml: nvcr.io/nvidia/pytorch:19.06-py3`

로 되어 있습니다.

nvidia docker image 버젼을 19.09로 바꿔서 실행하면 동작합니다.

`#nsml: nvcr.io/nvidia/pytorch:19.09-py3`

**Comment by kaen2891** [comment]
> 안녕하세요 @kaen2891 님!
> 저희 팀도 같은 현상을 겪었습니다. project의 setup.py를 열어보면 docker image가
> 
> `#nsml: nvcr.io/nvidia/pytorch:19.06-py3`
> 
> 로 되어 있습니다.
> 
> nvidia docker image 버젼을 19.09로 바꿔서 실행하면 동작합니다.
> 
> `#nsml: nvcr.io/nvidia/pytorch:19.09-py3`

안녕하세요 @HanSeokhyeon 님 . 알려주신대로 사용을 해보았는데 마찬가지로 계속 아래 부분에서 5분 이상 멈춰있습니다.
```
[2019-09-20 09:09:24,798 main.py:392 - main()] start
[2019-09-20 09:09:24,802 main.py:113 - train()] train() start
```
혹시 ```setup.py``` 내의 내용 외에도 추가하신 것이 있으신가요?

저희는 naver측에서 baseline code 제공해준것에, librosa를 추가하여 input feature만 다르게 뽑는것을 진행하고있습니다. 

아래는 저희 ```setup.py``` code입니다.

```
#nsml: nvcr.io/nvidia/pytorch:19.09-py3
from distutils.core import setup
import setuptools

setup(
    name='speech_hackathon',
    version='1.0',
    install_requires=[
        'python-Levenshtein',
        'librosa==0.6.3',
        'numpy==1.16.0'
    ]
)
```

**Comment by HanSeokhyeon** [comment]
@kaen2891 

```
#nsml: nvcr.io/nvidia/pytorch:19.09-py3
from distutils.core import setup
import setuptools

setup(
    name='speech_hackathon',
    version='1.0',
    install_requires=[
        'python-Levenshtein',
	    'librosa==0.7.0'
    ]
)
```

저희 팀의 setup.py code입니다.

librosa는 libsndfile1 패키지를 필요로 하므로 nsml_package.txt에 명시하여 설치가 필요한 것 같습니다.

`libsndfile1`

저희 팀 nsml_package.txt는 저렇게 명시하였고, 자세한 건
https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html
나와있습니다!
