### ISSUE TITLE
Label 파일 조회 방법 문의

### ISSUE THREAD

**Issue by amazingguni** [Naver-AI-Hackathon/AI-Speech#35]
**What is your NSML login ID?**

amazingguni

**Question**

라벨데이터를 읽어서 저희가 원하는 포멧으로 변환하려고 합니다.
train을 할 때에는 잘 읽어서 파일 작성까지 완료되는데, submit 시에 다음 메시지와 함께 에러가 발생합니다.

파일의 위치가 train, submit에서 다른 것으로 보이는데 이를 확인할 수 있는 방법이 있을까요?
`nsml submit --test`로 시도한 주소는 아래와 같습니다.

https://ai.nsml.navercorp.com/terminal/team125/sr-hack-2019-dataset/104

```
Traceback (most recent call last):
  File "main.py", line 467, in <module>
    main()
  File "main.py", line 356, in main
    generate_word_label_file(char_loader, TRAIN_LABEL_POS_PATH, TRAIN_LABEL_CHAR_PATH)
  File "/app/label_loader.py", line 80, in generate_word_label_file
    with open(char_train_label_path, 'r') as f_label:
FileNotFoundError: [Errno 2] No such file or directory: '/data/sr-hack-2019-dataset/train/train_label'
User session exited
```

**Comment by nsml-admin** [comment]
안녕하세요. 
유저가 label파일 조회는 불가능하게 되어있습니다.

**Comment by amazingguni** [comment]
넵 다른 방법을 찾아보겠습니다 :)
빠른 답변 감사드립니다.
