### ISSUE TITLE
nsml내에서 sudo 권한이 필요한 의존성 소프트웨어 설치 요청이 가능할까요.

### ISSUE THREAD

**Issue by dobby-seo** [Naver-AI-Hackathon/AI-Speech#37]
음성처리 프레임워크인 torchaudio 설치 과정 중 의존성 소프트웨어인 sox, libsox-dev, libsox-fmt-all 세가지 파일을 nsml_package.txt 내에 적어주었습니다. 그러나 도커 컨테이너 생성 중 오류가 뜨고 종료되었으며, 추측으로는 개인서버에서 테스트한 결과 sudo 권한이 필요하여 nsml상에서 apt-get -y update && apt-get -y install [package] 명령어로는 위의 소프트웨어를 설치할 수 없습니다.
피드백 부탁드리겠습니다!

추가적인 질문으로 nsml 사용이 아직 미숙하여 제대로 이해한지 모르겠는데, 혹시 개인 서버에서 학습 후 nsml.bind를 통하여서 모델을 submit하여 점수를 받을 수 있나요?

--서덕진 올림

**Comment by nsml-admin** [comment]
안녕하세요.
위의 필요한 라이브러리들을 현재 도커이미지에 저희가 추가해드리는건 불가능할것같습니다.
권장드리는 방법은 위의 라이브러리가 설치된 도커이미지를 구성하신후에 docker hub에 올린다음 nsml에서 해당하는 docker image를 사용하는것 입니다.

로컬에서 실험을 통해 좋은 아키텍처를 찾는것은 상관없지만 submit을 하는 모델의 학습은 nsml의 서버를 통해서 진행하셔야 합니다. (추후에 검사 예정입니다.)

감사합니다.
