### ISSUE TITLE
fork 시 error 문제

### ISSUE THREAD

**Issue by kaen2891** [Naver-AI-Hackathon/AI-Speech#38]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
kaen2891

**Question**
안녕하세요. fork시 문제가 생겨서 질문드리고싶습니다.

```/nsml fork SESSION``` 을 하였는데, 아래와 같은 오류가 생깁니다.

```
usage: main.py [-h] [--hidden_size HIDDEN_SIZE] [--layer_size LAYER_SIZE]
               [--dropout DROPOUT] [--bidirectional] [--use_attention]
               [--batch_size BATCH_SIZE] [--workers WORKERS]
               [--max_epochs MAX_EPOCHS] [--lr LR]
               [--teacher_forcing TEACHER_FORCING] [--max_len MAX_LEN]
               [--no_cuda] [--seed SEED] [--save_name SAVE_NAME] [--mode MODE]
               [--pause PAUSE]
main.py: error: unrecognized arguments: --iteration best
User session exited
```

main.py에는 --iteration 이 없는데, 혹시 이 부분을 어떻게 해결하면 좋을지 알려주시면 감사하겠습니다.

또한 fork 후 paused가 뜰 경우 제대로 동작이 되는지 궁금합니다.

**Comment by RaicLee** [comment]
단순 전에 훈련한 모델에서 fork 하여 훈련을 이어가시려고 하시면 nsml.load 를 사용하여 코드 내에서 모델을 불러와서 훈련하는 방법이 있습니다

**Comment by nsml-admin** [comment]
main.py에서 `--iteration` 옵션을 받을수 있게 추가한 후 다시한번 시도해 보시기 바랍니다.

` fork 후 paused가 뜰 경우 제대로 동작이 되는지 궁금합니다.` 

이부분이 잘 이해가 안되는데 좀더 자세히 설명해주실수 있으실까요?

**Comment by kaen2891** [comment]
fork 후 웹 사이트상 session내의 paused가 뜬 상태로 진행이 안되는데,

위에서 @RaicLee  님께서 load 방식을 알려주셔서 해결하였습니다.
