### ISSUE TITLE
선택한 세션들의 graph를 한 곳에서 볼 수 있으면 좋을것 같습니다

### ISSUE THREAD

**Issue by Yupjun** [Naver-AI-Hackathon/AI-Speech#39]
Diff 기능은 잘 쓰고 있습니다!

**Comment by nsml-admin** [comment]
[웹 화면](https://ai.nsml.navercorp.com/terminal)에서 여러 session들을 동시에 선택하실수 있습니다 (alt+ 마우스 왼쪽클릭)
그런후 graph탭을 클릭하면 graph를 같이 볼수 있습니다.

감사합니다.

**Comment by Yupjun** [comment]
아니 세상에 ㄷㄷ 감사합니다
