### ISSUE TITLE
세그멘테이션 오류 질문드립니다.

### ISSUE THREAD

**Issue by dobby-seo** [Naver-AI-Hackathon/AI-Speech#40]
![image](https://user-images.githubusercontent.com/33983084/65368961-2a986380-dc82-11e9-9834-8989dbb4021f.png)
위와 같은 오류가 발생했는데 혹시 자원의 문제일까요?

**Comment by DongKeon** [comment]
![Screenshot from 2019-09-22 03-04-10](https://user-images.githubusercontent.com/26243855/65377354-c6a78680-dce5-11e9-9c70-9e2cb273dd95.png)
저도 같은 오류가 나타나서 질문 드립니다
librosa로 변경하고 나서 나타나는 오류라 생각되는데 해결방법 없을까요?

**Comment by nsml-admin** [comment]
안녕하세요,
자세한건 세션이름을 알려주시면 확인할수 있겠지만,
대부분의 경우 위와같은 상황은 할당받은 memory보다 더 많은 memory를 사용했을때 발생하는 에러상황입니다.

https://github.com/Naver-AI-Hackathon/AI-Speech/issues/29 와 비슷한 이슈로 보입니다.

감사합니다.
