### ISSUE TITLE
Zombie 상태 세션 관련 질문 있습니다.

### ISSUE THREAD

**Issue by da-nyee** [Naver-AI-Hackathon/AI-Speech#41]
실행해둔 세션 두 개가 Zombie 상태에 빠져서 중단 후 삭제하려 합니다. 하지만 중단을 누르면 계속 'Your request has been failed'가 뜹니다. 이런 경우 세션 중단을 어떻게 해야 되나요? 따로 명령어가 있는 건가요??

**Comment by da-nyee** [comment]
현재 Zombie 상태인 세션 두 개입니다.
> team156/sr-hack-2019-dataset/12
> team156/sr-hack-2019-dataset/14

**Comment by Yupjun** [comment]
cmd 창에서 nsml rm -f 세션명 으로 지우시면 없어집니다.

**Comment by da-nyee** [comment]
> cmd 창에서 nsml rm -f 세션명 으로 지우시면 없어집니다.

삭제했습니다. 감사합니다! :)
