### ISSUE TITLE
nsml.report 질문드립니다

### ISSUE THREAD

**Issue by SaewonY** [Naver-AI-Hackathon/AI-Speech#42]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
SaewonY

**What is name of session in problem? (bug message or screenshot)**

세션명: nsml model ls team117/sr-hack-2019-dataset/211

![image](https://user-images.githubusercontent.com/40786348/65370550-e5c9f800-dc94-11e9-8eab-a5042ff33ac0.png)
![image](https://user-images.githubusercontent.com/40786348/65370569-2c1f5700-dc95-11e9-84e6-96bb1e4ce290.png)
![image](https://user-images.githubusercontent.com/40786348/65370557-04c88a00-dc95-11e9-857c-7c56b1db9ddb.png)

nsml model ls 했을때 checkpoint 저장된게 터미널 상에 나오는거랑 다른데요. 한 epoch씩 밀리는것 같은데 어떤식으로 해결해야 할 지 여쭤보고 싶습니다. 감사합니다.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by nsml-admin** [comment]
안녕하세요.

save를 하기전에 `nsml.report` 를 먼저해보시기 바랍니다.

감사합니다.

**Comment by SaewonY** [comment]
@nsml-admin 앗 감사합니다.
