### ISSUE TITLE
Submit시 sort()함수 오류 발생

### ISSUE THREAD

**Issue by shawrby** [Naver-AI-Hackathon/AI-Speech#45]
![323232](https://user-images.githubusercontent.com/54407464/65380952-9382e880-dd21-11e9-9296-7a5dbe04558a.PNG)

NSML로 트레이닝 할때는 문제가 없는데,
Submit시 sort() 함수가 오류 발생합니다.

해결 방안에 대해 문의드립니다.

**Comment by shawrby** [comment]
참고로 sort()의 input은 Tensor 입니다.

**Comment by nsml-admin** [comment]
안녕하세요.
submit시에 전체 에러 메세지가 안나와서 디버깅이 힘든 상황으로 보이는데요,

`submit -t` 명령어로 확인해 보시면 전체 에러메세지를 확인 하고 디버깅이 가능한 상황으로 보입니다.(https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/submit_a_session.html?highlight=submit)

감사합니다.

**Comment by shawrby** [comment]
![11111](https://user-images.githubusercontent.com/54407464/65384802-a3bab800-dd61-11e9-8f2c-41cbebd5755d.PNG)

전체 에러는 다음과 같습니다.

**Comment by nsml-admin** [comment]
해당 부분은 유저 코드의 영역에서 발생한 에러상황으로 보여서 저희가 디버깅을 도와드리기에는 한계가 있습니다.

인터넷 검색이나 api문서를 확인해보시고 해결하시는방법이 있을것 같습니다.

**Comment by nsml-user** [comment]
에러 메세지를 보니 enc_len으로 들어가는 input이 None 값인거 같습니다. 이 변수에 대한 디버깅을 다시 해보시길..

**Comment by shawrby** [comment]
답변 감사합니다!
