### ISSUE TITLE
팀원 깃허브 계정이 nsml에 등록이 되어있지 않습니다.

### ISSUE THREAD

**Issue by inkoon** [Naver-AI-Hackathon/AI-Speech#46]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**
안녕하세요?
초록괴물 팀 입니다.
저희 팀원 중 1명이 제대로 등록되지 않은 것 같습니다.
확인해주시고 알려주시면 감사하겠습니다.

**Comment by nsml-admin** [comment]
안녕하세요
초록괴물팀은 팀원이 총2명인것으로 확인되어 나머지 한분은 github 계정이
'comecom' 이분인것으로 보입니다. 
플랫폼상 등록이 되어있는데 제대로 등록이 안된거 같다는거는 
어떤부분이 안되서 등록이 안되어 있다고 말씀하시는 건지 알 수 있을까요??

CLI 로그인시 comecom web으로 로그인시 github에 comecom 이걸로 로그인이 되어있어야합니다.

**Comment by inkoon** [comment]
참가 신청을 총 3명으로 신청했으나 지금 2명으로 진행이 되고 있는 것 같습니다.
참가신청서 상으로는 보이는데 nsml login이나 리더보드에 보이지 않습니다.
 
팀원3 개인 정보 입니다.
 
-----Original Message-----

**Comment by nsml-admin** [comment]
추가로 되어있었네요,,, 혹시 마지막 팀원 계정이 https://github.com/hoon2j 맞나요?

**Comment by inkoon** [comment]
https://github.com/boychaboy 이거 입니다! 


2019. 9. 23. 16:38, nsml-admin <notifications@github.com> 작성:

**Comment by nsml-admin** [comment]
등록되었습니다. 확인해보시고 안될경우 말씀해주세요!

**Comment by boychaboy** [comment]
등록되었습니다. 감사합니다!
