### ISSUE TITLE
데이터 Sampling Rate 질문 

### ISSUE THREAD

**Issue by DongKeon** [Naver-AI-Hackathon/AI-Speech#47]
training data를 봤을때 16K로 되어있긴 하지만 
약 4K 이후에는 값이 거의 없다고 보이는데, 녹음이 8K channel 환경에서 진행된것인지 궁금합니다.

**Comment by nsml-user** [comment]
> training data를 봤을때 16K로 되어있긴 하지만
> 약 4K 이후에는 값이 거의 없다고 보이는데, 녹음이 8K channel 환경에서 진행된것인지 궁금합니다.

네 맞습니다. 8kHz sampling으로 녹음되었습니다.
