### ISSUE TITLE
Credit 관련 질문

### ISSUE THREAD

**Issue by RaicLee** [Naver-AI-Hackathon/AI-Speech#52]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
RaicLee

**Question**
추가적인 credit 배분 예정이 있을것인지 궁금해서 질문드립니다

**Comment by bluebrush** [comment]
@RaicLee 님, 자원 현황을 고려하여 추가 credit을 일괄 충전하였습니다.

**Comment by RaicLee** [comment]
감사합니다!
