### ISSUE TITLE
NSML 세션 종료 요청

### ISSUE THREAD

**Issue by shawrby** [Naver-AI-Hackathon/AI-Speech#59]
안녕하세요,

NSML Running 시 잘 못 구동하여, 급히 터미널에서 ctrl+c를 눌러 종료했으나, 
이미 allocate가 계속해서 진행되고 있습니다.

급히 아래의 세션 종료 요청드립니다..
team 136, '딥마을이장님' 팀 입니다.
![image](https://user-images.githubusercontent.com/54407464/65418339-2e211b80-de37-11e9-96a0-abaff12ea29e.png)

감사합니다.

**Comment by RaicLee** [comment]
nsml rm -f team136/sr-hack-2019-dataset/109 를 터미널에 치시면 됩니다

**Comment by shawrby** [comment]
진심으로 감사합니다!!
