### ISSUE TITLE
team21/ sr-hack-2019-dataset/189 번 세션 종료 요청

### ISSUE THREAD

**Issue by haeinha** [Naver-AI-Hackathon/AI-Speech#65]
안녕하세요 DongDang 팀의 하해인입니다.
submit을 했는데 종료가 안돼서
team21/ sr-hack-2019-dataset/189 번 submit 세션 종료 요청드립니다.
감사합니다
하해인드림

**Comment by RaicLee** [comment]
nsml rm -f team21/sr-hack-2019-dataset/189 하시면 됩니다

**Comment by haeinha** [comment]
감사합니다
