### ISSUE TITLE
nsml run시 fail

### ISSUE THREAD

**Issue by Ella77** [Naver-AI-Hackathon/AI-Speech#68]
..Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
...
Building docker image. It might take for a while

한참 기다렸는데 아래와 같은 에러메시지가 떴습니다

team213/sr-hack-2019-dataset/2: Fail to build session
[]
Done
Error: Fail to build docker image. Please Contact Dev team

**Comment by RaicLee** [comment]
저도 어쩔때마다 이렇게 뜬적이 있습니다만 여러번 시도하면 되더라고요
