### ISSUE TITLE
좀비 세션 중지 요청

### ISSUE THREAD

**Issue by inkoon** [Naver-AI-Hackathon/AI-Speech#69]
좀비을 중지하려고 하면 "Your request has been failed." 이라는 에러와 함께 중지되지 않습니다.
어떻게 하면 좀비 세션을 중지할 수 있을까요?

**Comment by RaicLee** [comment]
nsml rm -f 를 사용하시기 바랍니다

**Comment by inkoon** [comment]
> nsml rm -f 를 사용하시기 바랍니다

감사합니다!!
