### ISSUE TITLE
Data Augmentation 관련

### ISSUE THREAD

**Issue by fromakim** [Naver-AI-Hackathon/AI-Speech#71]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Linux Mint 19 Tara
- **client version(please show nsml --version)**:
Built: 2019-09-06T11:25:12+09:00
Go: go1.12.9
GOARCH: amd64
GOOS: linux
Revision: 7b0bb1503fa9b3994273bd258bc68b31272907cb (not-modified)
Preconfigured connection: ai-cli.nsml.navercorp.com:443

#### WEB
- **Brower (chrome, firfox, etc)**: Firefox
- **URL**:

**What is your NSML login ID?**
fromakim

**Question**
Data Augmentation 관련

안녕하세요. 이번 NSML 관련하여 해커톤을 진행하던 중 Data Augmentation 과정에서 오류가 생겨서 문의 드리게 되었습니다.

다름이 아니라 Data Augmentation을 위하여 soundfile.write() 함수를 사용하고 있는데, 이것이 local에서는 괜찮게 돌아가지만 nsml 클라우드로 실행하면 아래와 같은 에러 메시지가 나옵니다.

![image](https://user-images.githubusercontent.com/28501405/65672958-e42d7500-e084-11e9-9ba3-502905805e66.png)

그래서 혹시, train_dataset에 데이터를 추가하는 것이 금지되어 있는지 여쭙고 싶습니다. 감사합니다.

**Comment by nsml-admin** [comment]
안녕하세요.
train_dataset에 데이터를 추가하는것은 금지되어 있습니다.

감사합니다.
