### ISSUE TITLE
credit 관련 질문입니다

### ISSUE THREAD

**Issue by RaicLee** [Naver-AI-Hackathon/AI-Speech#74]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

앞으로도 추가적인 credit 배정 일정이 있는지 궁금하여 질문드립니다

**Comment by bluebrush** [comment]
@RaicLee 마지막 충전하였습니다. credit 부족을 없을 것으로 예상됩니다. 다만 동시사용 GPU수가 조정되었습니다.

**Comment by RaicLee** [comment]
감사합니다!
