### ISSUE TITLE
submit 시 에러 문제 (transport is closing)

### ISSUE THREAD

**Issue by JJANGJJANGMEE** [Naver-AI-Hackathon/AI-Speech#77]
**Question**

며칠 전 이슈에도 있었던 것 같은데, 
submit 테스트 도중 다음과 같은 에러가 발생합니다.
이후 세션이 좀비가 되어 세션을 정지할 수 없고 삭제해야 했습니다.

해당 세션 삭제이후, 한번 더 submit -t를 수행하였으나, 동일 에러가 발생했습니다.

<img width="725" alt="스크린샷 2019-09-28 21 47 04" src="https://user-images.githubusercontent.com/16406936/65817394-521e9b80-e241-11e9-8507-dccdbbaba564.png">

**Comment by kaen2891** [comment]
@JJANGJJANGMEE 님,
저희는 새벽(한가한 시간)에 제출해보니 그 문제를 해결할 수 있었습니다.

도움이 되시면 좋겠습니다.

**Comment by JJANGJJANGMEE** [comment]
@kaen2891 님, 
저희도 시간을 두고 좀 더 기다렸다가 하니까, 다시 되더라구요. 
그때 그때 잠시 발생하는 문제인가 보네요.
답변 감사합니다!
