### ISSUE TITLE
세션 멈춤이 안됩니다

### ISSUE THREAD

**Issue by HyunjiEllenPak** [Naver-AI-Hackathon/AI-Speech#78]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

안녕하세요. 팀 Absolutely 입니다.
세션 561, 581번이 무한 할당 또는 테스트 제출 완료된 세션인데 세션이 멈춰지지가 않습니다. 세션 정지 부탁드립니다.
감사합니다.

**Comment by RaicLee** [comment]
nsml rm -f team(번호)/sr-hack-2019-dataset/(번호) 를 터미널에 쓰시면 될것 같습니다
