### ISSUE TITLE
데이터셋이 현재 오픈이 되어있나요?

### ISSUE THREAD

**Issue by Yupjun** [Naver-AI-Hackathon/AI-Speech#8]
아니면 계정을 할당해서 주시는지 궁금합니다.

**Comment by Yupjun** [comment]
그리고 크레딧도 자정 기준으로 1872 크레딧이 부여되는 건지 궁금합니다

**Comment by bluebrush** [comment]
@Yupjun 님, 불편을 드려서 죄송합니다.
현재, NSML에서는 dataset을 접근하실 수 있습니다. 

train용 dataset은 repo의 release 탭에 준비될 예정입니다.(2시간 이내로 예상됩니다.)

**Comment by Yupjun** [comment]
그러면 NSML cmd 에서도 pull로 받을 수 있는지 궁금합니다!

**Comment by bluebrush** [comment]
@Yupjun 님, 관련정보가 https://github.com/clovaai/speech_hackathon_2019/blob/master/README.md 에 업데이트되었습니다.
