### ISSUE TITLE
리소스 제한 요청드립니다

### ISSUE THREAD

**Issue by HyunjiEllenPak** [Naver-AI-Hackathon/AI-Speech#80]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**What is name of session in problem? (bug message or screenshot)**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

안녕하세요. nsml 리소스 사용관련하여 요청사항이 있어서 글 남깁니다.

현재 참가중인 팀이 100팀, 사용가능한 전체 GPU가 100개인데 팀당 GPU제한이 3개입니다.  예선 마감이 얼마 남지 않아서 매일같이 리소스가 98~100을 웃돌고 있습니다.
이에 저희 팀은 세션을 제대로 돌리지 못하고 있습니다. 위의 제한과 같이 팀당 GPU 3개를 점령하고 있으면 저희와 같이 GPU사용을 못하는 팀들도 있을 것 같습니다.  

예선 마감때까지 팀당 GPU사용을 2개로 제한해 주실 수 있을까요?

**Comment by amazingguni** [comment]
동의합니다. 최소한 팀당 1개는 학습이 가능한 환경이 되었으면 합니다.

**Comment by bluebrush** [comment]
팀당 2개로 설정하였습니다. 상황 지켜보고 추가 조치 검토하겠습니다.
