### ISSUE TITLE
nsml run을 실행했다가 바로 종료했는데 세션이 삭제되지 않습니다

### ISSUE THREAD

**Issue by developtkr** [Naver-AI-Hackathon/AI-Speech#86]
nsml run을 실행했다가 바로 종료했는데 세션이 삭제되지 않습니다

세션정지/삭제 모두 작동하지 않는중입니다 ㅠ

제가 강제로 종료한게 문제인 것 같은데 어떻게 해결해야할까요?

아래는 종료 시점 로그입니다.

세션 이름은 
team224/sr-hack-2019-dataset/70
입니다.

====================== 
time="2019/10/01 20:07:34.293" level=info msg="run.sh 201 B - done (25/28 89.29%) (12 MiB/12 MiB 99.96%)"
time="2019/10/01 20:07:34.297" level=info msg="run_nsml.sh 257 B - start"
time="2019/10/01 20:07:34.302" level=info msg="run_nsml.sh 257 B - done (26/28 92.86%) (12 MiB/12 MiB 99.96%)"
time="2019/10/01 20:07:34.311" level=info msg="setup.py 244 B - start"
time="2019/10/01 20:07:34.314" level=info msg="setup.py 244 B - done (27/28 96.43%) (12 MiB/12 MiB 99.96%)"
time="2019/10/01 20:07:34.319" level=info msg="wavio.py 4.5 KiB - start"
time="2019/10/01 20:07:34.322" level=info msg="wavio.py 4.5 KiB - done (28/28 100.00%) (12 MiB/12 MiB 100.00%)"
..Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
...
Building docker image. It might take for a while
...
time="2019/10/01 20:07:38.942" level=info msg="run aborted: Interrupted by user"

**Comment by RaicLee** [comment]
nsml rm -f 를 사용하시기 바랍니다

**Comment by developtkr** [comment]
감사합니다
