### ISSUE TITLE
baseline code submit 이 안되고 있습니다...

### ISSUE THREAD

**Issue by DShomin** [Naver-AI-Hackathon/AI-Speech#9]
nsml submit -t 옵션은 정상적으로 작동하고 있지만 nsml submit 을 했을때는 아래 애러코드가 발생하고 있습니다.
[error code]
time="2019/09/17 18:12:38.245" level=warning msg="Rate limit exceeded: remained time: 1s"
time="2019/09/17 18:12:38.250" level=fatal msg="Rate limit exceeded"

**Comment by bluebrush** [comment]
@DShomin 님, 혹시, 오류가 지속되시면 session ID알려주시면 추가확인진행할 수 있을것 같습니다.

**Comment by DShomin** [comment]
답변 감사합니다. 
session ID: team79/sr-hack-2019-dataset/1 

지금 slack에서도 이와 비슷한 이슈로 대화가 오가고 있는데 저만 그런것 같지 않습니다.

**Comment by bluebrush** [comment]
@DShomin , @SaewonY 님, 불편을 드려서 죄송합니다. 방금 오류확인되어 수정되었습니다.
