### ISSUE TITLE
제출 점수 문의

### ISSUE THREAD

**Issue by HyunjiEllenPak** [Naver-AI-Hackathon/AI-Speech#91]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

안녕하세요. 팀 Absolutely입니다.
저희가 그동안 점수 제출을 잘 해왔었는데, 어제 제출에서 마이너스 점수가 나왔습니다. 
테스트 제출을 해보았을 때는 이전과 같이 멀쩡한 문장이 나왔는데, 제출을 하니 마이너스 점수가 나와서 문의드립니다. 
세션 번호 1122번 제출에서 발생한 문제인데, 테스트 제출은 잘 되는데 제출시에만 이러는 이유가 있을까요?ㅠ

감사합니다

@bluebrush @nsml-admin

**Comment by dreamgonfly** [comment]
metric의 최저점수가 0이라는 건 어디서 알 수 있나요? cer은 계산 방식에 따르면 1을 넘을 수 있습니다.
