### ISSUE TITLE
할당 자원이 사라졌습니다.

### ISSUE THREAD

**Issue by gusalsdmlwlq** [Naver-AI-Hackathon/AI-Speech#96]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
gusalsdmlwlq

**Question**
갑자기 nsml상에서 제 아이디로 할당된 자원이 모두 사라져서 학습과 제출을 할 수 없는 상황이 되었습니다.
gpu와 cpu 모두 0으로 할당되어 있는데 해결 부탁드립니다.
매콤쌈무 팀입니다.

**Comment by elzino** [comment]
행복코딩팀도 같은 증상입니다. 해결부탁드립니다.

**Comment by sooftware** [comment]
2시부터 할당하려고 하는 것 아닐까요 ??
오늘 2시부터 결선 시작입니다 !!

**Comment by gusalsdmlwlq** [comment]
앗 그럴수도 있겠네요.
일단 기다려봐야겠네요.
